# Form implementation generated from reading ui file 'C:\Users\hanka.jos\Documents\hopefully_working_directory\openMotor\uilib/views/forms\AboutDialog.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_AboutDialog(object):
    def setupUi(self, AboutDialog):
        AboutDialog.setObjectName("AboutDialog")
        AboutDialog.setWindowModality(QtCore.Qt.WindowModality.ApplicationModal)
        AboutDialog.resize(848, 389)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(AboutDialog.sizePolicy().hasHeightForWidth())
        AboutDialog.setSizePolicy(sizePolicy)
        AboutDialog.setMinimumSize(QtCore.QSize(610, 180))
        AboutDialog.setMaximumSize(QtCore.QSize(16777215, 16777215))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:\\Users\\hanka.jos\\Documents\\hopefully_working_directory\\openMotor\\uilib/views/forms\\resources/oMIconCycles.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        AboutDialog.setWindowIcon(icon)
        AboutDialog.setToolTip("")
        AboutDialog.setModal(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(AboutDialog)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetFixedSize)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetFixedSize)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.labelImage = QtWidgets.QLabel(parent=AboutDialog)
        self.labelImage.setMinimumSize(QtCore.QSize(128, 128))
        self.labelImage.setMaximumSize(QtCore.QSize(128, 128))
        self.labelImage.setText("")
        self.labelImage.setPixmap(QtGui.QPixmap("C:\\Users\\hanka.jos\\Documents\\hopefully_working_directory\\openMotor\\uilib/views/forms\\../../../resources/oMIconCyclesSmall.png"))
        self.labelImage.setObjectName("labelImage")
        self.horizontalLayout_2.addWidget(self.labelImage)
        self.labelText = QtWidgets.QLabel(parent=AboutDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelText.sizePolicy().hasHeightForWidth())
        self.labelText.setSizePolicy(sizePolicy)
        self.labelText.setObjectName("labelText")
        self.horizontalLayout_2.addWidget(self.labelText)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=AboutDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(AboutDialog)
        self.buttonBox.accepted.connect(AboutDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(AboutDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(AboutDialog)

    def retranslateUi(self, AboutDialog):
        _translate = QtCore.QCoreApplication.translate
        AboutDialog.setWindowTitle(_translate("AboutDialog", "About openMotor"))
        self.labelText.setText(_translate("AboutDialog", "<html><head/><body><p>openMotor ###</p><p>Released under the GNU GPL V3 License.</p><p><a href=\"https://github.com/reilleya/openMotor\"><span style=\" text-decoration: underline; color:#0000ff;\">https://github.com/reilleya/openMotor</span></a></p><p><br/>Warning: Rocket motors can be dangerous! Always verify calculations before testing a motor, <br/>and test far enough away from people and structures to avoid damage. The results from this<br/>program are provided as an estimate and come with no guarantees.</p></body></html>"))
