# Form implementation generated from reading ui file 'C:\Users\hanka.jos\Documents\hopefully_working_directory\openMotor\uilib/views/forms\CSVExporter.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_CSVExporter(object):
    def setupUi(self, CSVExporter):
        CSVExporter.setObjectName("CSVExporter")
        CSVExporter.resize(400, 300)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:\\Users\\hanka.jos\\Documents\\hopefully_working_directory\\openMotor\\uilib/views/forms\\resources/oMIconCycles.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        CSVExporter.setWindowIcon(icon)
        self.verticalLayout = QtWidgets.QVBoxLayout(CSVExporter)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=CSVExporter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.channelSelector = ChannelSelector(parent=CSVExporter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.channelSelector.sizePolicy().hasHeightForWidth())
        self.channelSelector.setSizePolicy(sizePolicy)
        self.channelSelector.setObjectName("channelSelector")
        self.verticalLayout.addWidget(self.channelSelector)
        self.grainSelector = GrainSelector(parent=CSVExporter)
        self.grainSelector.setObjectName("grainSelector")
        self.verticalLayout.addWidget(self.grainSelector)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=CSVExporter)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(CSVExporter)
        self.buttonBox.accepted.connect(CSVExporter.accept) # type: ignore
        self.buttonBox.rejected.connect(CSVExporter.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(CSVExporter)

    def retranslateUi(self, CSVExporter):
        _translate = QtCore.QCoreApplication.translate
        CSVExporter.setWindowTitle(_translate("CSVExporter", "Export CSV"))
        self.label.setText(_translate("CSVExporter", "Simulation must have been run to export a CSV."))
        self.channelSelector.setTitle(_translate("CSVExporter", "Channels"))
        self.grainSelector.setTitle(_translate("CSVExporter", "Grains"))
from uilib.widgets.channelSelector import ChannelSelector
from uilib.widgets.grainSelector import GrainSelector
