# Form implementation generated from reading ui file 'C:\Users\hanka.jos\Documents\hopefully_working_directory\openMotor\uilib/views/forms\EngExporter.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_EngExporterDialog(object):
    def setupUi(self, EngExporterDialog):
        EngExporterDialog.setObjectName("EngExporterDialog")
        EngExporterDialog.resize(400, 400)
        EngExporterDialog.setMinimumSize(QtCore.QSize(400, 400))
        EngExporterDialog.setMaximumSize(QtCore.QSize(400, 400))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:\\Users\\hanka.jos\\Documents\\hopefully_working_directory\\openMotor\\uilib/views/forms\\resources/oMIconCycles.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        EngExporterDialog.setWindowIcon(icon)
        self.verticalLayout = QtWidgets.QVBoxLayout(EngExporterDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=EngExporterDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.motorStats = CollectionEditor(parent=EngExporterDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.motorStats.sizePolicy().hasHeightForWidth())
        self.motorStats.setSizePolicy(sizePolicy)
        self.motorStats.setObjectName("motorStats")
        self.verticalLayout.addWidget(self.motorStats)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=EngExporterDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(EngExporterDialog)
        self.buttonBox.accepted.connect(EngExporterDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(EngExporterDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(EngExporterDialog)

    def retranslateUi(self, EngExporterDialog):
        _translate = QtCore.QCoreApplication.translate
        EngExporterDialog.setWindowTitle(_translate("EngExporterDialog", "Export .eng file"))
        self.label.setText(_translate("EngExporterDialog", "Simulation must have been run to export a RASP .eng file."))
from uilib.widgets.collectionEditor import CollectionEditor
