# Form implementation generated from reading ui file 'C:\Users\hanka.jos\Documents\hopefully_working_directory\openMotor\uilib/views/forms\GrainPreview.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_GrainPreview(object):
    def setupUi(self, GrainPreview):
        GrainPreview.setObjectName("GrainPreview")
        GrainPreview.resize(330, 175)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(GrainPreview.sizePolicy().hasHeightForWidth())
        GrainPreview.setSizePolicy(sizePolicy)
        GrainPreview.setMinimumSize(QtCore.QSize(330, 175))
        GrainPreview.setMaximumSize(QtCore.QSize(330, 175))
        self.verticalLayout = QtWidgets.QVBoxLayout(GrainPreview)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(parent=GrainPreview)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.TabPosition.South)
        self.tabWidget.setObjectName("tabWidget")
        self.tabAlerts = QtWidgets.QListWidget()
        self.tabAlerts.setObjectName("tabAlerts")
        self.tabWidget.addTab(self.tabAlerts, "")
        self.tabFace = GrainPreviewGraph()
        self.tabFace.setObjectName("tabFace")
        self.tabWidget.addTab(self.tabFace, "")
        self.tabRegression = GrainPreviewGraph()
        self.tabRegression.setObjectName("tabRegression")
        self.tabWidget.addTab(self.tabRegression, "")
        self.tabAreaGraph = GrainPreviewGraph()
        self.tabAreaGraph.setObjectName("tabAreaGraph")
        self.tabWidget.addTab(self.tabAreaGraph, "")
        self.verticalLayout.addWidget(self.tabWidget)

        self.retranslateUi(GrainPreview)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(GrainPreview)

    def retranslateUi(self, GrainPreview):
        _translate = QtCore.QCoreApplication.translate
        GrainPreview.setWindowTitle(_translate("GrainPreview", "Form"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabAlerts), _translate("GrainPreview", "Alerts"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabFace), _translate("GrainPreview", "Face"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabRegression), _translate("GrainPreview", "Regression"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabAreaGraph), _translate("GrainPreview", "Area Graph"))
from uilib.widgets.grainPreviewGraph import GrainPreviewGraph
