# Form implementation generated from reading ui file 'C:\Users\hanka.jos\Documents\hopefully_working_directory\openMotor\uilib/views/forms\ImageExporter.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ImageExporter(object):
    def setupUi(self, ImageExporter):
        ImageExporter.setObjectName("ImageExporter")
        ImageExporter.resize(400, 300)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:\\Users\\hanka.jos\\Documents\\hopefully_working_directory\\openMotor\\uilib/views/forms\\resources/oMIconCycles.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        ImageExporter.setWindowIcon(icon)
        self.verticalLayout = QtWidgets.QVBoxLayout(ImageExporter)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=ImageExporter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.independent = ChannelSelector(parent=ImageExporter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.independent.sizePolicy().hasHeightForWidth())
        self.independent.setSizePolicy(sizePolicy)
        self.independent.setObjectName("independent")
        self.verticalLayout.addWidget(self.independent)
        self.dependent = ChannelSelector(parent=ImageExporter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dependent.sizePolicy().hasHeightForWidth())
        self.dependent.setSizePolicy(sizePolicy)
        self.dependent.setObjectName("dependent")
        self.verticalLayout.addWidget(self.dependent)
        self.grainSelector = GrainSelector(parent=ImageExporter)
        self.grainSelector.setObjectName("grainSelector")
        self.verticalLayout.addWidget(self.grainSelector)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=ImageExporter)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(ImageExporter)
        self.buttonBox.accepted.connect(ImageExporter.accept) # type: ignore
        self.buttonBox.rejected.connect(ImageExporter.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(ImageExporter)

    def retranslateUi(self, ImageExporter):
        _translate = QtCore.QCoreApplication.translate
        ImageExporter.setWindowTitle(_translate("ImageExporter", "Export Image"))
        self.label.setText(_translate("ImageExporter", "Simulation must have been run to export an image."))
        self.independent.setTitle(_translate("ImageExporter", "X Axis"))
        self.dependent.setTitle(_translate("ImageExporter", "Y Axis"))
        self.grainSelector.setTitle(_translate("ImageExporter", "Grains"))
from uilib.widgets.channelSelector import ChannelSelector
from uilib.widgets.grainSelector import GrainSelector
