# Form implementation generated from reading ui file 'C:\Users\hanka.jos\Documents\hopefully_working_directory\openMotor\uilib/views/forms\NozzlePreview.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_NozzlePreview(object):
    def setupUi(self, NozzlePreview):
        NozzlePreview.setObjectName("NozzlePreview")
        NozzlePreview.resize(330, 175)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(NozzlePreview.sizePolicy().hasHeightForWidth())
        NozzlePreview.setSizePolicy(sizePolicy)
        NozzlePreview.setMinimumSize(QtCore.QSize(330, 175))
        NozzlePreview.setMaximumSize(QtCore.QSize(330, 175))
        self.verticalLayout = QtWidgets.QVBoxLayout(NozzlePreview)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(parent=NozzlePreview)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.TabPosition.South)
        self.tabWidget.setObjectName("tabWidget")
        self.tabAlerts = QtWidgets.QListWidget()
        self.tabAlerts.setObjectName("tabAlerts")
        self.tabWidget.addTab(self.tabAlerts, "")
        self.tabCrossSection = QtWidgets.QGraphicsView()
        self.tabCrossSection.setObjectName("tabCrossSection")
        self.tabWidget.addTab(self.tabCrossSection, "")
        self.verticalLayout.addWidget(self.tabWidget)

        self.retranslateUi(NozzlePreview)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(NozzlePreview)

    def retranslateUi(self, NozzlePreview):
        _translate = QtCore.QCoreApplication.translate
        NozzlePreview.setWindowTitle(_translate("NozzlePreview", "Form"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabAlerts), _translate("NozzlePreview", "Alerts"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabCrossSection), _translate("NozzlePreview", "Cross Section"))
