# Form implementation generated from reading ui file 'C:\Users\hanka.jos\Documents\hopefully_working_directory\openMotor\uilib/views/forms\Preferences.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_PreferencesDialog(object):
    def setupUi(self, PreferencesDialog):
        PreferencesDialog.setObjectName("PreferencesDialog")
        PreferencesDialog.resize(414, 415)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:\\Users\\hanka.jos\\Documents\\hopefully_working_directory\\openMotor\\uilib/views/forms\\resources/oMIconCycles.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        PreferencesDialog.setWindowIcon(icon)
        self.verticalLayout = QtWidgets.QVBoxLayout(PreferencesDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(parent=PreferencesDialog)
        self.tabWidget.setObjectName("tabWidget")
        self.tabGeneral = QtWidgets.QWidget()
        self.tabGeneral.setObjectName("tabGeneral")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tabGeneral)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(parent=self.tabGeneral)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.settingsEditorGeneral = SettingsEditor(parent=self.tabGeneral)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.settingsEditorGeneral.sizePolicy().hasHeightForWidth())
        self.settingsEditorGeneral.setSizePolicy(sizePolicy)
        self.settingsEditorGeneral.setObjectName("settingsEditorGeneral")
        self.verticalLayout_2.addWidget(self.settingsEditorGeneral)
        self.tabWidget.addTab(self.tabGeneral, "")
        self.tabUnits = QtWidgets.QWidget()
        self.tabUnits.setObjectName("tabUnits")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tabUnits)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.settingsEditorUnits = SettingsEditor(parent=self.tabUnits)
        self.settingsEditorUnits.setObjectName("settingsEditorUnits")
        self.verticalLayout_3.addWidget(self.settingsEditorUnits)
        self.tabWidget.addTab(self.tabUnits, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=PreferencesDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(PreferencesDialog)
        self.tabWidget.setCurrentIndex(0)
        self.buttonBox.accepted.connect(PreferencesDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(PreferencesDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(PreferencesDialog)

    def retranslateUi(self, PreferencesDialog):
        _translate = QtCore.QCoreApplication.translate
        PreferencesDialog.setWindowTitle(_translate("PreferencesDialog", "Preferences"))
        self.label.setText(_translate("PreferencesDialog", "Set the default motor configuration. Every motor you create will copy its configuration from these settings, and they can be changed for each motor individually in the grain table. "))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabGeneral), _translate("PreferencesDialog", "General"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabUnits), _translate("PreferencesDialog", "Units"))
from uilib.widgets.settingsEditor import SettingsEditor
