# Form implementation generated from reading ui file 'C:\Users\hanka.jos\Documents\hopefully_working_directory\openMotor\uilib/views/forms\PropellantPreview.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_PropellantPreview(object):
    def setupUi(self, PropellantPreview):
        PropellantPreview.setObjectName("PropellantPreview")
        PropellantPreview.resize(400, 416)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(PropellantPreview.sizePolicy().hasHeightForWidth())
        PropellantPreview.setSizePolicy(sizePolicy)
        self.verticalLayout = QtWidgets.QVBoxLayout(PropellantPreview)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(parent=PropellantPreview)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(0, 220))
        self.tabWidget.setMaximumSize(QtCore.QSize(16777215, 220))
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.TabPosition.South)
        self.tabWidget.setObjectName("tabWidget")
        self.tabAlerts = QtWidgets.QListWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabAlerts.sizePolicy().hasHeightForWidth())
        self.tabAlerts.setSizePolicy(sizePolicy)
        self.tabAlerts.setMaximumSize(QtCore.QSize(16777215, 220))
        self.tabAlerts.setObjectName("tabAlerts")
        self.tabWidget.addTab(self.tabAlerts, "")
        self.tabBurnRate = BurnrateGraph()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabBurnRate.sizePolicy().hasHeightForWidth())
        self.tabBurnRate.setSizePolicy(sizePolicy)
        self.tabBurnRate.setMaximumSize(QtCore.QSize(16777215, 220))
        self.tabBurnRate.setObjectName("tabBurnRate")
        self.tabWidget.addTab(self.tabBurnRate, "")
        self.verticalLayout.addWidget(self.tabWidget)

        self.retranslateUi(PropellantPreview)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(PropellantPreview)

    def retranslateUi(self, PropellantPreview):
        _translate = QtCore.QCoreApplication.translate
        PropellantPreview.setWindowTitle(_translate("PropellantPreview", "Form"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabAlerts), _translate("PropellantPreview", "Alerts"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabBurnRate), _translate("PropellantPreview", "Burn Rate"))
from uilib.widgets.burnrateGraph import BurnrateGraph
