# Form implementation generated from reading ui file 'C:\Users\hanka.jos\Documents\hopefully_working_directory\openMotor\uilib/views/forms\PropMenu.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_PropellantDialog(object):
    def setupUi(self, PropellantDialog):
        PropellantDialog.setObjectName("PropellantDialog")
        PropellantDialog.setWindowModality(QtCore.Qt.WindowModality.ApplicationModal)
        PropellantDialog.resize(850, 800)
        PropellantDialog.setMinimumSize(QtCore.QSize(850, 800))
        PropellantDialog.setMaximumSize(QtCore.QSize(16777215, 16777215))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:\\Users\\hanka.jos\\Documents\\hopefully_working_directory\\openMotor\\uilib/views/forms\\resources/oMIconCycles.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        PropellantDialog.setWindowIcon(icon)
        self.verticalLayout = QtWidgets.QVBoxLayout(PropellantDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, -1, 0, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(-1, 12, 0, -1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.listWidgetPropellants = QtWidgets.QListWidget(parent=PropellantDialog)
        self.listWidgetPropellants.setMaximumSize(QtCore.QSize(150, 16777215))
        self.listWidgetPropellants.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectItems)
        self.listWidgetPropellants.setSelectionRectVisible(True)
        self.listWidgetPropellants.setObjectName("listWidgetPropellants")
        self.verticalLayout_2.addWidget(self.listWidgetPropellants)
        self.pushButtonNewPropellant = QtWidgets.QPushButton(parent=PropellantDialog)
        self.pushButtonNewPropellant.setObjectName("pushButtonNewPropellant")
        self.verticalLayout_2.addWidget(self.pushButtonNewPropellant)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButtonEdit = QtWidgets.QPushButton(parent=PropellantDialog)
        self.pushButtonEdit.setObjectName("pushButtonEdit")
        self.horizontalLayout_2.addWidget(self.pushButtonEdit)
        self.pushButtonDelete = QtWidgets.QPushButton(parent=PropellantDialog)
        self.pushButtonDelete.setObjectName("pushButtonDelete")
        self.horizontalLayout_2.addWidget(self.pushButtonDelete)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.line = QtWidgets.QFrame(parent=PropellantDialog)
        self.line.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.line)
        self.propEditor = PropellantEditor(parent=PropellantDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.propEditor.sizePolicy().hasHeightForWidth())
        self.propEditor.setSizePolicy(sizePolicy)
        self.propEditor.setObjectName("propEditor")
        self.horizontalLayout.addWidget(self.propEditor)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(PropellantDialog)
        QtCore.QMetaObject.connectSlotsByName(PropellantDialog)

    def retranslateUi(self, PropellantDialog):
        _translate = QtCore.QCoreApplication.translate
        PropellantDialog.setWindowTitle(_translate("PropellantDialog", "Propellant Editor"))
        self.pushButtonNewPropellant.setText(_translate("PropellantDialog", "New"))
        self.pushButtonEdit.setText(_translate("PropellantDialog", "Edit"))
        self.pushButtonDelete.setText(_translate("PropellantDialog", "Delete"))
from uilib.widgets.propellantEditor import PropellantEditor
