# Form implementation generated from reading ui file 'C:\Users\hanka.jos\Documents\hopefully_working_directory\openMotor\uilib/views/forms\SimulatingDialog.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_SimProgressDialog(object):
    def setupUi(self, SimProgressDialog):
        SimProgressDialog.setObjectName("SimProgressDialog")
        SimProgressDialog.setWindowModality(QtCore.Qt.WindowModality.ApplicationModal)
        SimProgressDialog.resize(400, 100)
        SimProgressDialog.setMinimumSize(QtCore.QSize(400, 100))
        SimProgressDialog.setMaximumSize(QtCore.QSize(400, 100))
        SimProgressDialog.setModal(True)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:\\Users\\hanka.jos\\Documents\\hopefully_working_directory\\openMotor\\uilib/views/forms\\resources/oMIconCycles.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        SimProgressDialog.setWindowIcon(icon)
        self.verticalLayout = QtWidgets.QVBoxLayout(SimProgressDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=SimProgressDialog)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.progressBar = QtWidgets.QProgressBar(parent=SimProgressDialog)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout.addWidget(self.progressBar)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=SimProgressDialog)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(SimProgressDialog)
        QtCore.QMetaObject.connectSlotsByName(SimProgressDialog)

    def retranslateUi(self, SimProgressDialog):
        _translate = QtCore.QCoreApplication.translate
        SimProgressDialog.setWindowTitle(_translate("SimProgressDialog", "Simulating"))
        self.label.setText(_translate("SimProgressDialog", "Running simulation..."))
