# Form implementation generated from reading ui file 'C:\Users\hanka.jos\Documents\hopefully_working_directory\openMotor\uilib/views/forms\TabularEditor.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_TabularEditor(object):
    def setupUi(self, TabularEditor):
        TabularEditor.setObjectName("TabularEditor")
        TabularEditor.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(TabularEditor)
        self.verticalLayout.setObjectName("verticalLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(parent=TabularEditor)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.stackedWidget.addWidget(self.page_2)
        self.verticalLayout.addWidget(self.stackedWidget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, -1, -1, 6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButtonAdd = QtWidgets.QPushButton(parent=TabularEditor)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonAdd.sizePolicy().hasHeightForWidth())
        self.pushButtonAdd.setSizePolicy(sizePolicy)
        self.pushButtonAdd.setObjectName("pushButtonAdd")
        self.horizontalLayout.addWidget(self.pushButtonAdd)
        self.pushButtonRemove = QtWidgets.QPushButton(parent=TabularEditor)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonRemove.sizePolicy().hasHeightForWidth())
        self.pushButtonRemove.setSizePolicy(sizePolicy)
        self.pushButtonRemove.setObjectName("pushButtonRemove")
        self.horizontalLayout.addWidget(self.pushButtonRemove)
        self.line = QtWidgets.QFrame(parent=TabularEditor)
        self.line.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.line)
        self.pushButtonLeft = QtWidgets.QPushButton(parent=TabularEditor)
        self.pushButtonLeft.setMinimumSize(QtCore.QSize(30, 0))
        self.pushButtonLeft.setMaximumSize(QtCore.QSize(30, 16777215))
        self.pushButtonLeft.setObjectName("pushButtonLeft")
        self.horizontalLayout.addWidget(self.pushButtonLeft)
        self.labelCurrentTab = QtWidgets.QLabel(parent=TabularEditor)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelCurrentTab.sizePolicy().hasHeightForWidth())
        self.labelCurrentTab.setSizePolicy(sizePolicy)
        self.labelCurrentTab.setObjectName("labelCurrentTab")
        self.horizontalLayout.addWidget(self.labelCurrentTab)
        self.pushButtonRight = QtWidgets.QPushButton(parent=TabularEditor)
        self.pushButtonRight.setMinimumSize(QtCore.QSize(30, 0))
        self.pushButtonRight.setMaximumSize(QtCore.QSize(30, 16777215))
        self.pushButtonRight.setObjectName("pushButtonRight")
        self.horizontalLayout.addWidget(self.pushButtonRight)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(TabularEditor)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(TabularEditor)

    def retranslateUi(self, TabularEditor):
        _translate = QtCore.QCoreApplication.translate
        TabularEditor.setWindowTitle(_translate("TabularEditor", "Form"))
        self.pushButtonAdd.setText(_translate("TabularEditor", "Add Pressure Range"))
        self.pushButtonRemove.setText(_translate("TabularEditor", "Remove Pressure Range"))
        self.pushButtonLeft.setText(_translate("TabularEditor", "<"))
        self.labelCurrentTab.setText(_translate("TabularEditor", "1/1"))
        self.pushButtonRight.setText(_translate("TabularEditor", ">"))
